name: aplicacion_turistica_cadiz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cadiz.jpg
    - assets/torreTavira.jpg
    - assets/murallaSanCarlo.jpg
    - assets/teatroRomano.jpg
    - assets/monumentoConst.jpg
    - assets/puertaTierra.webp
    - assets/arcoPopulo.jpg
    - assets/resumenCadiz.jpg